// angular/src/app/components/articles/articles.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { Global } from '../../services/global';


@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  @Input() articles: Article[];
  public url: string;

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
    // console.log(this.articles);
  }

}

<div class="loading" *ngIf="!articles">
    Cargando...
</div>

<div class="loading" *ngIf="articles && articles.length == 0">
    No hay articulos para mostrar.
</div>

<div id="articles" *ngIf="articles">
      <article class="article-item" *ngFor="let article of articles">
          <div class="image-wrap">
              <img src="{{ url + 'get-image/' + article.image }}" alt="{{ article.image }}" *ngIf="article.image"/>
              <img src="../../../assets/images/default.png" alt="{{ article.image }}" *ngIf="!article.image"/>
          </div>

          <h2>{{ article.title }}</h2>
          <span class="date">
              {{ article.date |  amLocale: 'es' | amTimeAgo}}
          </span>
          <a [routerLink]="['/blog/articulo', article._id]" >Leer más</a>

          <div class="clearfix"></div>
      </article>
  </div>

// vuepp/src/components/Articles.vue
<template>
  <div id="articleList">
    <article class="article-item" v-for="article in articles" :key="article.id">
      <div class="image-wrap">
        <img
          :src="url + 'get-image/' + article.image"
          :alt="article.title"
          v-if="article.image"
        />
        <img
          src="../assets/images/default.jpeg"
          :alt="article.title"
          v-if="!article.image"
        />
      </div>

      <h2>{{ article.title }}</h2>
      <span class="date">{{ article.date }}</span>
      <a href="#">Leer más</a>

      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
export default {
  name: "Articles",
  props: ["articles"],
};
</script>
