// vuepp/src/components/Formulario.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <h2 class="subheader">Formulario</h2>
        <form class="mid-form" @submit.prevent = "mostrarUsuario()">
          <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" v-model= "user.nombre" />
            <div v-if= "submitted && !$v.user.nombre.required">Este campo es obligatorio</div>
            <div v-if= "submitted && !$v.user.nombre.minLength">Este campo debe tener mas caracteres</div>
          </div>

          <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" name="apellidos" v-model= "user.apellidos" />
            <div v-if= "submitted && !$v.user.apellidos.required">Este campo es obligatorio</div>
            <div v-if= "submitted && !$v.user.apellidos.minLength">Este campo debe tener mas caracteres</div>
          </div>

          <div class="form-group">
            <label for="bio">Biografia</label>
            <textarea name="bio" v-model= "user.bio"></textarea>
            <div v-if= "submitted && !$v.user.bio.required">Este campo es obligatorio</div>
            <div v-if= "submitted && !$v.user.bio.minLength">Este campo debe tener mas caracteres</div>
            
          </div>

          <div class="form-group radibuttons">
            <input type="radio" name="genero" value="hombre"  v-model= "user.genero"/> Hombre
            <input type="radio" name="genero" value="mujer" v-model= "user.genero" /> Mujer
            <input type="radio" name="genero" value="otro" v-model= "user.genero" /> Otro
          </div>

          <div class="clearfix"></div>

          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>

        <div class= "datos" v-if= "user.nombre && user.apellidos">
          {{user.nombre + ' ' + user.apellidos}}
        </div>

      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>


<script>
import {required, minLength} from 'vuelidate/lib/validators';

import Sidebar from "./Sidebar.vue";

export default {
  name: "Formulario",
  components: {
    Sidebar,
  },
 
  validations: {
    user: {
      nombre: {
        required,
        minLength: minLength(2)  
      },
      apellidos: {
        required,
        minLength: minLength(2)  
      },
      bio: {
        required,
        minLength: minLength(12)  
      }
    }
    
  },
  data(){
    return {
      
      submitted: false,
      user: {
        nombre: '',
        apellidos: '',
        bio: '',
        genero: ''
      }
    }    
  },
  methods: {
    mostrarUsuario(){
      console.log(this.user);
      this.submitted = true; 

      this.$v.$touch();
      if(this.$v.$invalid){
        return false; 
      }

      alert('Validacion pasada.')
    }
  }  
};
</script>

// angular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;
  public campo2: string;

  constructor() {
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };
  }

  ngOnInit(): void {
  }

  onSubmit(){
    alert('Formulario enviado');
    console.log(this.user);
  }

  hasClick(){
    alert('Has dado click.');
  }

  hasSalido(){
    alert('Has salido.');
  }

  hasDadoEnter(){
    alert('Has dado ENTER.');
  }

}

<app-slider [nombre]="'FORMULARIO'" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Formulario</h1>
    
    <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" 
          required pattern="^[A-Za-z\s]{1,}[\.]{0,1}[A-Za-z\s]{0,}$"/>
        <small *ngIf="!nombre.valid && nombre.touched">
          El nombre no es válido</small>
      </div>

      <div class="form-group">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" 
        required pattern="^[A-Za-z\s]{1,}[\.]{0,1}[A-Za-z\s]{0,}$"/>
        <small *ngIf="!apellidos.valid && apellidos.touched">
          Los apellidos no son válidos</small>
      </div>

      <div class="form-group">
        <label for="bio">Biografia</label>
        <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
        <small *ngIf="!bio.valid && bio.touched">
          El campo de Biografía no es válido</small>
      </div>

      <div class="form-group radibuttons" >
        <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.genero" required /> Hombre
        <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" /> Mujer
        <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.genero" /> Otro
        <small *ngIf="!genero.valid && genero.touched">
          El género no ha sido seleccionado</small>
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>

    </form>

    <hr>
    <!-- <h2 class="subheader">Eventos</h2>
    <button (click)="hasClick()">Dale click!!!</button>
    <br><br>
    <input type="text" [(ngModel)]="campo" (blur)="hasSalido()">
    {{campo}}
    <br><br>
    <input type="text" [(ngModel)]="campo2" (keyup.enter)="hasDadoEnter()"> -->
    <br><br>

  </section>

  <app-sidebar></app-sidebar>
</div>
